"use client";

import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, ExternalLink, LoaderCircle, RefreshCw, XCircle } from "lucide-react";

interface Candidate { title: string; url: string; domain: string; kind: string; embedUrl?: string; approvalStatus?: "approved" | "rejected" }
interface Approval extends Candidate { id: string; compositionSlug: string; status: "approved" | "rejected"; approvedAt: string }
interface SongOption { slug: string; title: string; raga: string }

export function MediaReview({ songs, initialApprovals }: { songs: SongOption[]; initialApprovals: Approval[] }) {
  const [slug, setSlug] = useState(songs[0]?.slug || ""); const [items, setItems] = useState<Candidate[]>([]); const [approvals, setApprovals] = useState(initialApprovals); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const selected = songs.find((song) => song.slug === slug);
  async function load() { if (!slug) return; setLoading(true); setError(""); try { const response = await fetch(`/api/v1/songs/${slug}/enrichment?review=1`, { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Could not load candidates"); setItems([...body.media, ...body.lyricSources]); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not load candidates"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [slug]);
  const statusMap = useMemo(() => new Map(approvals.filter((item) => item.compositionSlug === slug).map((item) => [item.url, item.status])), [approvals, slug]);
  async function decide(item: Candidate, status: "approved" | "rejected") { setError(""); const response = await fetch("/api/v1/admin/approvals", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ compositionSlug: slug, title: item.title, url: item.url, domain: item.domain, kind: item.kind, embedUrl: item.embedUrl, status }) }); const body = await response.json(); if (!response.ok) { setError(body.error || "Could not save decision"); return; } setApprovals((current) => [body.item, ...current.filter((approval) => !(approval.compositionSlug === slug && approval.url === item.url))]); }
  return <><div className="review-toolbar"><label>Composition<select value={slug} onChange={(event) => setSlug(event.target.value)}>{songs.map((song) => <option value={song.slug} key={song.slug}>{song.title} · {song.raga}</option>)}</select></label><button className="primary-button" onClick={load} disabled={loading}><RefreshCw className={loading ? "spin" : ""} size={15} /> Refresh discovery</button></div>{selected && <p className="muted small">Reviewing internet candidates for <strong>{selected.title}</strong>. Play or open each result before approval.</p>}{error && <div className="notice">{error}</div>}{loading && !items.length && <div className="card empty"><LoaderCircle className="spin" /><p>Searching configured providers…</p></div>}<div className="review-list">{items.map((item) => { const status = statusMap.get(item.url); return <article className="card review-item" key={item.url}>{item.embedUrl && item.kind === "youtube" ? <div className="review-preview"><iframe src={item.embedUrl} title={item.title} loading="lazy" allowFullScreen /></div> : <div className="result-symbol">{item.kind === "lyrics" ? "Aa" : "♪"}</div>}<div><span className={`pill ${status === "approved" ? "green" : status === "rejected" ? "saffron" : ""}`}>{status || "pending"} · {item.kind}</span><h3>{item.title}</h3><a className="text-link small" href={item.url} target="_blank" rel="noreferrer">Open {item.domain} <ExternalLink size={13} /></a></div><div className="review-actions"><button className="approve" onClick={() => decide(item, "approved")}><CheckCircle2 size={17} /> Approve</button><button className="reject" onClick={() => decide(item, "rejected")}><XCircle size={17} /> Reject</button></div></article>; })}</div></>;
}
