import Link from "next/link";
import { redirect } from "next/navigation";
import { AlertTriangle, BookOpenCheck, Bot, Database, Link2Off, Music2 } from "lucide-react";
import { compositions, ragas, tutorials } from "@/lib/catalog";
import { hasAdminSession } from "@/lib/admin-session";

export const metadata = { title: "Editorial dashboard" };
export default async function AdminPage() {
  if (!(await hasAdminSession())) redirect("/admin/login");
  const recent = [...ragas.slice(0, 3).map((r) => ({ title: r.name.en, type: "Raga", state: r.state })), ...compositions.slice(0, 3).map((c) => ({ title: c.title.en, type: "Composition", state: c.state }))];
  return <div className="admin-shell"><aside className="admin-side"><strong className="serif" style={{ fontSize: "1.2rem" }}>Editorial studio</strong><div style={{ marginTop: 28 }}><Link className="active" href="/admin">Overview</Link><Link href="/admin/review">Media review</Link><Link href="/corrections">Corrections</Link></div></aside><section className="admin-main"><span className="eyebrow">Authenticated editor</span><h1 className="serif" style={{ fontSize: "2.7rem", margin: "8px 0 5px" }}>Catalog overview</h1><p className="muted">Review internet discoveries before they are treated as trusted catalog media.</p><div className="notice" style={{ margin: "24px 0" }}><AlertTriangle size={16} style={{ verticalAlign: "middle", marginRight: 8 }} />The 300-song launch target is editorial work, not generated seed data. Import only records that have passed source and rights review.</div><div className="admin-grid"><div className="card metric"><Database size={19} /><span className="muted small">Ragas</span><strong>{ragas.length}</strong></div><div className="card metric"><Music2 size={19} /><span className="muted small">Compositions</span><strong>{compositions.length}</strong></div><div className="card metric"><BookOpenCheck size={19} /><span className="muted small">Tutorials</span><strong>{tutorials.length}</strong></div><Link href="/admin/review" className="card metric"><Link2Off size={19} /><span className="muted small">Open review queue</span><strong>→</strong></Link></div><table className="admin-table"><thead><tr><th>Record</th><th>Type</th><th>Workflow</th><th>Provenance</th></tr></thead><tbody>{recent.map((item) => <tr key={item.title}><td><strong>{item.title}</strong></td><td>{item.type}</td><td><span className="status">{item.state}</span></td><td>Source attached</td></tr>)}</tbody></table><div className="card" style={{ padding: 25, marginTop: 25, display: "flex", gap: 20 }}><Bot color="#a8452d" /><div><strong>AI drafting boundary</strong><p className="muted small">The protected API accepts approved source excerpts and returns a structured bilingual draft. It cannot publish, assign a raga, estimate tonic, or determine copyright.</p></div></div></section></div>;
}
